from enum import Enum


class AllureFeature(str, Enum):

    AUTHENTICATION = "AUTHENTICATION"
    ADDITIONAL_FILTERS = "ADDITIONAL_FILTERS"
    BALANCING = "BALANCING"
    CUSTOM_CONFIG = "CUSTOM_CONFIG"
    DEFAULT_CONFIG = "DEFAULT_CONFIG"
    FILTERS = "FILTERS"
    ALL_FILTERS = "ALL_FILTERS"
    MIRRORING = "MIRRORING"
    PORTS = "PORTS"
    LOOPBACK_PORTS = "LOOPBACK_PORTS"
    INGRESS_GROUPS = "INGRESS_GROUPS"
    NODES = "NODES"
    SELECTIONS = "SELECTIONS"
    EGRESS_GROUPS = "EGRESS_GROUPS"