from enum import Enum


class AllureFeature(str, Enum):

    AUTHENTICATION = "AUTHENTICATION"
    ADDITIONAL_FILTERS = "ADDITIONAL_FILTERS"
    BALANCING = "BALANCING"
    CUSTOM_CONFIG = "CUSTOM_CONFIG"
    DEFAULT_CONFIG = "DEFAULT_CONFIG"
    FILTERS = "FILTERS"
    MIRRORING = "MIRRORING"
    PORTS = "PORTS"
    LOOPBACK_PORTS = "LOOPBACK_PORTS"