from enum import Enum


class AllureTag(str, Enum):

    REGRESSION = "REGRESSION"
    AUTHENTICATION = "AUTHENTICATION"
    ADDITIONAL_FILTERS = "ADDITIONAL_FILTERS"
    BALANCING = "BALANCING"

    GET_ENTITY = "GET_ENTITY"
    GET_ENTITIES = "GET_ENTITIES"
    CREATE_ENTITY = "CREATE_ENTITY"
    UPDATE_ENTITY = "UPDATE_ENTITY"
    DELETE_ENTITY = "DELETE_ENTITY"
    VALIDATE_ENTITY = "VALIDATE_ENTITY"
    SUCCESS_LOGIN = "SUCCESS_LOGIN"