from enum import Enum


class AllureTag(str, Enum):

    REGRESSION = "REGRESSION"
    AUTHENTICATION = "AUTHENTICATION"
    ADDITIONAL_FILTERS = "ADDITIONAL_FILTERS"
    BALANCING = "BALANCING"
    CUSTOM_CONFIG = "CUSTOM_CONFIG"
    DEFAULT_CONFIG = "DEFAULT_CONFIG"
    FILTERS = "FILTERS"
    ALL_FILTERS = "ALL_FILTERS"
    MIRRORING = "MIRRORING"
    PORTS = "PORTS"
    PORTS_ALL = "PORTS_ALL"
    PORT_STATUS = "PORT_STATUS"
    LOOPBACK_PORTS = "LOOPBACK_PORTS"
    INGRESS_GROUPS = "INGRESS_GROUPS"
    NODES = "NODES"
    SELECTIONS = "SELECTIONS"
    SWITCH_INFO = "SWITCH_INFO"
    EGRESS_GROUPS = "EGRESS_GROUPS"
    ANALYSIS_PORTS = "ANALYSIS_PORTS"
    PSF_FORMAT = "PSF_FORMAT"
    PSF_DMAC = "PSF_DMAC"
    MIRROR_FILTER = "MIRROR_FILTER"
    PSF_MIRROR_FILTER = "PSF_MIRROR_FILTER"

    GET_ENTITY = "GET_ENTITY"
    GET_ENTITIES = "GET_ENTITIES"
    CREATE_ENTITY = "CREATE_ENTITY"
    UPDATE_ENTITY = "UPDATE_ENTITY"
    DELETE_ENTITY = "DELETE_ENTITY"
    VALIDATE_ENTITY = "VALIDATE_ENTITY"

    POSITIVE_TEST = "POSITIVE_TEST"
    NEGATIVE_TEST = "NEGATIVE_TEST"
    FLAKY_TEST = "FLAKY_TEST"

    SUCCESS_LOGIN = "SUCCESS_LOGIN"